export default {
  UPDATE_TEXT: 'UPDATE_TEXT',
  UPDATE_TO_LOCALE: 'UPDATE_TO_LOCALE',
  ADD_LOCALE: 'ADD_LOCALE',
  ADD_ENTRY: 'ADD_ENTRY', // 添加词条
  BATCH_ADD_ENTRY: 'BATCH_ADD_ENTRY',
  UPDATE_MODE: 'UPDATE_MODE',
  DELETE_ENTRY: 'DELETE_ENTRY',
};
